apps/authentication/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_login import UserMixin

from sqlalchemy.orm import relationship

from apps import db, login_manager

from apps.authentication.util import hash_pass
from werkzeug.security import generate_password_hash

from datetime import datetime
import pytz

def get_bogota_time():
    
    bogota_tz = pytz.timezone('America/Bogota')
    ahora_utc = datetime.now(pytz.utc)
    ahora = ahora_utc.astimezone(bogota_tz)
    return ahora
class UserBusiness(db.Model):
    __tablename__ = 'user_business'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    business_id = db.Column(db.Integer, db.ForeignKey('businesses.id'), nullable=False)

    # Define relationships to Users and Businesses
    user = db.relationship("Users", back_populates="user_businesses")
    business = db.relationship("Businesses", back_populates="user_businesses")

    def __repr__(self):
        return f"<UserBusiness(id={self.id}, user_id={self.user_id}, business_id={self.business_id})>"
    
class Users(db.Model, UserMixin):

    __tablename__ = 'users'

    id            = db.Column(db.Integer, primary_key=True)
    username      = db.Column(db.String(64), unique=True)
    email         = db.Column(db.String(64), unique=True)
    password      = db.Column(db.LargeBinary)
    type_user = db.Column(db.Integer, default=0)
    phone = db.Column(db.String(20), unique=True)
    email_token = db.Column(db.String(255), unique=True)
    active_account = db.Column(db.Boolean, default=False)
    token_created_at = db.Column(db.DateTime, default=get_bogota_time())

    # cash_register_sessions = relationship("CashRegisterSessions", back_populates="user")
    sessions = relationship("SessionLogs", back_populates="user")
    # Relationship to UserBusiness
    user_businesses = db.relationship("UserBusiness", back_populates="user")

    def __repr__(self):
        return str(self.username) 

    def encrypt_password(self, password):
        return hash_pass(password)
    
class SessionLogs(db.Model):
    __tablename__ = 'session_logs'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    login_time = db.Column(db.DateTime, nullable=False)
    logout_time = db.Column(db.DateTime)

    # Establish relationship with Users
    user = relationship("Users", back_populates="sessions")

    def __repr__(self):
        return f"<SessionLogs(id={self.id}, user_id={self.user_id}, login_time={self.login_time}, logout_time={self.logout_time})>"
    
    
class BusinessTypes(db.Model):
    __tablename__ = 'business_types'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True, nullable=False)
    # Define the relationship to Businesses
    businesses = db.relationship("Businesses", back_populates="business_type")

    def __repr__(self):
        return f"<BusinessTypes(id={self.id}, name='{self.name}')>"

class Businesses(db.Model):
    __tablename__ = 'businesses'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), nullable=False)
    payment_status = db.Column(db.Boolean, default=False)
    business_type_id = db.Column(db.Integer, db.ForeignKey('business_types.id'))
    email = db.Column(db.String(64), unique=True)
    phone = db.Column(db.String(20), unique=True)
    is_authorized = db.Column(db.Boolean, default=False)

    # Define the relationship to BusinessTypes
    business_type = db.relationship("BusinessTypes", back_populates="businesses")
    # Relationship to UserBusiness
    user_businesses = db.relationship("UserBusiness", back_populates="business")

    def __repr__(self):
        return f"<Businesses(id={self.id}, name='{self.name}')>"

    
# class CashRegisterSessions(db.Model):
#     __tablename__ = 'cash_register_sessions'

#     id = db.Column(db.Integer, primary_key=True)
#     user_id = db.Column(db.Integer, db.ForeignKey('Users.id'), nullable=False)
#     open_time = db.Column(db.TIMESTAMP, nullable=False, default=datetime.utcnow)
#     close_time = db.Column(db.TIMESTAMP)
#     initial_cash = db.Column(db.Numeric, nullable=False)
#     # total_transactions = db.Column(db.Numeric, default=0)

#     # Relación con Usuarios
#     user = relationship("Users", back_populates="cash_register_sessions")

#     def __repr__(self):
#         return (f"<CashRegisterSessions(id={self.id}, user_id={self.user_id}, "
#                 f"open_time={self.open_time}, close_time={self.close_time}, "
#                 f"initial_cash={self.initial_cash})>")
      
@login_manager.user_loader
def user_loader(id):
    return Users.query.filter_by(id=id).first()


@login_manager.request_loader
def request_loader(request):
    username = request.form.get('username')
    user = Users.query.filter_by(username=username).first()
    return user if user else None

apps/authentication/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField,SubmitField,BooleanField
from wtforms.validators import Email, DataRequired,EqualTo,Length

# login and registration


class LoginForm(FlaskForm):
    username = StringField('Username',
                         id='username_login',
                         validators=[DataRequired()])
    password = PasswordField('Password',
                             id='pwd_login',
                             validators=[DataRequired()])


class CreateAccountForm(FlaskForm):
    username = StringField('Username',
                         id='username_create',
                         validators=[DataRequired()])
    email = StringField('Email',
                      id='email_create',
                      validators=[DataRequired(), Email()])
    password = PasswordField('Password',
                             id='pwd_create',
                             validators=[DataRequired()])
    confirm = PasswordField(
        "Confirmar Contraseña",
        validators=[
            DataRequired(),
            EqualTo("password", message="Passwords must match."),
        ],
    )
    phone = StringField("Telefono", validators=[DataRequired()])
    submit = SubmitField("Registrarse")
    
class RegistrationForm(FlaskForm):
    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=8)])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    phone = StringField("Telefono", validators=[DataRequired()])

    toc = BooleanField('Terms of Service', validators=[DataRequired()])
    
class EmailForm(FlaskForm):
    """User Log-in Form."""
 
    email = StringField(
        "Email", validators=[DataRequired(), Email(message="Ingrese un email valido")]
    )     
    submit = SubmitField("Recuperar contraseña")

class PassForm(FlaskForm):
    password = PasswordField("Password", validators=[DataRequired(),Length(min=6, message="Ingrese una contraseña segura"),],)
    confirm = PasswordField("Confirm password", validators=[DataRequired(),EqualTo("password", message="Las contraseñas no coinciden"),],)
    submit = SubmitField("Cambiar")

apps/authentication/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'authentication_blueprint',
    __name__,
    url_prefix=''
)

apps/authentication/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import render_template, redirect, request, url_for,flash
from flask_login import (
    current_user,
    login_user,
    logout_user
)

from apps import db, login_manager,mail,socketio
from apps.authentication import blueprint
from apps.authentication.forms import LoginForm, CreateAccountForm,EmailForm,PassForm,RegistrationForm
from apps.authentication.models import *
from apps.authentication.util import verify_pass
from flask import Flask, render_template, request, jsonify,session
from itsdangerous import URLSafeTimedSerializer
from flask_socketio import SocketIO, emit

from flask_mail import Message
from flask import current_app as app
import os
import time
@blueprint.route('/')
def route_default():
    return redirect(url_for('authentication_blueprint.login'))


@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm()



    if request.method == 'POST':
        # read form data
        username = request.form.get('username')
        email = request.form.get('email')
        password = request.form.get('password')
            # Locate user
        user = Users.query.filter_by(username=username).first()
        # Check the password
        if user and verify_pass(password, user.password):

            login_user(user)

            if user.type_user == 1:
                return redirect(url_for('admin_blueprint.business_panel'))
            elif user.type_user == 2:
                return redirect(url_for('order_blueprint.order'))

        
        # Something (user or pass) is not ok
        return render_template('authentication/sign-in.html',
                               msg='Usuario o contraseña incorrectos',
                               form=login_form)

    else:
        return render_template('authentication/sign-in.html',
                        form=login_form)
    # if not current_user.is_authenticated:
    #     return render_template('accounts/login.html',
    #                            form=login_form)
    
# @blueprint.route('/login', methods=['GET', 'POST'])
# def login():
#     login_form = LoginForm()



#     if login_form.validate_on_submit():
#         # read form data
#         username = login_form.username.data
#         password = login_form.password.data
#             # Locate user
#         user = Users.query.filter_by(username=username).first()
#         # Check the password
#         if user and verify_pass(password, user.password):

#             login_user(user)

#             if user.type_user == 1:
#                 return redirect(url_for('admin_blueprint.business_panel'))
#             elif user.type_user == 2:
#                 return redirect(url_for('order_blueprint.order'))

        
#         # Something (user or pass) is not ok
#         return render_template('accounts/login.html',
#                                msg='Usuario o contraseña incorrectos',
#                                form=login_form)

#     else:
#         return render_template('accounts/login.html',
#                         form=login_form)
#     # if not current_user.is_authenticated:
#     #     return render_template('accounts/login.html',
#     #                            form=login_form)



@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    print(app.config['DOMAIN'])
    if request.method == 'POST':
        # Obtener datos del request
        username = request.form.get('username')
        email = request.form.get('email')
        phone = request.form.get('phone')
        password = request.form.get('password')
        toc = request.form.get('toc')

        # Verificar si el usuario ya existe
        if Users.query.filter_by(username=username).first():
            return jsonify(success=False, message='Nombre de usuario ya registrado')

        # Verificar si el email ya existe
        if Users.query.filter_by(email=email).first():
            return jsonify(success=False, message='Correo electrónico ya registrado')

        # Verificar si el teléfono ya existe
        if Users.query.filter_by(phone=phone).first():
            return jsonify(success=False, message='Teléfono ya registrado')

        # Generar el token seguro
        serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
        email_token = serializer.dumps(email, salt=app.config['SECURITY_PASSWORD_SALT'])

        # Crear el enlace de activación
        activate_link = url_for('authentication_blueprint.activate', token=email_token, _external=True)

        # Configurar el correo electrónico
        email_info = Message('Confirma tu registro en Imperionex.com', sender=app.config['MAIL_USERNAME'], recipients=[email])
        email_info.body = render_template('authentication/email/template-verify-email.html', link=activate_link)
        email_info.html = render_template('authentication/email/template-verify-email.html', link=activate_link)

        # Adjuntar imágenes al correo electrónico
        for i in range(1, 6):
            img_name = f'image-{i}.png'
            img_path = os.path.join(app.static_folder, 'metronic/media/email/verify_email', img_name)
            with app.open_resource(img_path) as fp:
                cid = f'<imagen_{i}>'
                headers = {'Content-ID': cid}
                email_info.attach(img_name, 'image/png', fp.read(), headers=headers)

        # Enviar el correo
        mail.send(email_info)

        # Crear y guardar el usuario
        user = Users(email=email, phone=phone, password=Users().encrypt_password(password),
                     email_token=email_token, username=username, type_user=1)
        db.session.add(user)
        db.session.commit()

        # Guardar el correo en la sesión para mostrarlo en la página de verificación
        session['registered_email'] = email

        return jsonify(success=True, message="Registro exitoso! Revisa tu correo para activar tu cuenta.")

    return render_template('authentication/sign-up.html')

@blueprint.route('/login/activate/<token>', methods=['GET'])
def activate(token):
    try:
        serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
        email = serializer.loads(token, salt=app.config['SECURITY_PASSWORD_SALT'], max_age=86400)  # Expira en 24 hora
    except:
        return jsonify(success=False, message='El enlace de activación es inválido o ha expirado.')

    # Buscar al usuario por el email
    user = Users.query.filter_by(email=email).first()

    if user and user.email_token == token:
        user.active_account = 1
        db.session.add(user)
        db.session.commit()
        login_user(user)
        return redirect(url_for('authentication_blueprint.multi_steps_register'))
    else:
        return jsonify(success=False, message='El enlace de activación es inválido.')


@blueprint.route('/verify_email', methods=['GET', 'POST'])
def verify_email():
    email = session.get('registered_email', None)

    if request.method == 'POST':
        if email:
            # Reenviar el correo de activación
            serializer = URLSafeTimedSerializer(app.config['SECRET_KEY'])
            email_token = serializer.dumps(email, salt=app.config['SECURITY_PASSWORD_SALT'])
            
            user = Users.query.filter_by(email=email).first()
            user.email_token = email_token
            db.session.commit()
            
            activate_link = url_for('authentication_blueprint.activate', token=email_token, _external=True)

            email_info = Message('Reenvío de activación de cuenta en Imperionex.com', sender=app.config['MAIL_USERNAME'], recipients=[email])
            email_info.body = render_template('authentication/email/template-verify-email.html', link=activate_link)
            email_info.html = render_template('authentication/email/template-verify-email.html', link=activate_link)
            # Adjuntar imágenes al correo electrónico
            for i in range(1, 6):
                img_name = f'image-{i}.png'
                img_path = os.path.join(app.static_folder, 'metronic/media/email/verify_email', img_name)
                with app.open_resource(img_path) as fp:
                    cid = f'<imagen_{i}>'
                    headers = {'Content-ID': cid}
                    email_info.attach(img_name, 'image/png', fp.read(), headers=headers)
                
            mail.send(email_info)
            return jsonify(success=True, message='Correo de activación reenviado. Revisa tu bandeja de entrada.')

        else:
            return jsonify(success=False, message='No se encontró un correo registrado. Intenta registrarte nuevamente.')

    return render_template('authentication/general/verify-email.html', email=email)

@socketio.on('start_timer')
def handle_start_timer(data):
    total_time = data['time']
    for remaining_time in range(total_time, 0, -1):
        time.sleep(1)  # Esperar 1 segundo
        emit('update_timer', {'time': remaining_time}, broadcast=True)
    # Enviar mensaje cuando el temporizador ha terminado
    emit('timer_done', {}, broadcast=True)
@blueprint.route('/multi_steps_register', methods=['GET', 'POST'])
def multi_steps_register():
    queryTypes =BusinessTypes.query.all()
    if request.method == 'POST':
        business_name = request.form.get('business_name')
        business_type = request.form.get('business_type')
                # Verificar si el usuario ya ha enviado una solicitud
        existing_business = UserBusiness.query.filter_by(user_id=current_user.id).first()
        if existing_business:
            return jsonify(success=False, message='Ya has enviado una solicitud.')
        
        business = Businesses(name=business_name,business_type_id=business_type)
        db.session.add(business)
        
        userBusiness = UserBusiness(user_id=current_user.id,business_id=business.id)
        db.session.add(userBusiness)
        
        db.session.commit()

apps/templates/authentication/new-password.html
{% extends "layouts/authentication/base_auth.html" %}
{% block content_auth %}
<form class="form w-100" novalidate="novalidate" id="kt_new_password_form" data-kt-redirect-url="authentication/layouts/corporate/sign-in.html" action="#">
	<!--begin::Heading-->
	<div class="text-center mb-10">
		<!--begin::Title-->
		<h1 class="text-gray-900 fw-bolder mb-3">Setup New Password</h1>
		<!--end::Title-->
		<!--begin::Link-->
		<div class="text-gray-500 fw-semibold fs-6">Have you already reset the password ? 
		<a href="authentication/layouts/corporate/sign-in.html" class="link-primary fw-bold">Sign in</a></div>
		<!--end::Link-->
	</div>
	<!--begin::Heading-->
	<!--begin::Input group-->
	<div class="fv-row mb-8" data-kt-password-meter="true">
		<!--begin::Wrapper-->
		<div class="mb-1">
			<!--begin::Input wrapper-->
			<div class="position-relative mb-3">
				<input class="form-control bg-transparent" type="password" placeholder="Password" name="password" autocomplete="off" />
				<span class="btn btn-sm btn-icon position-absolute translate-middle top-50 end-0 me-n2" data-kt-password-meter-control="visibility">
					<i class="ki-duotone ki-eye-slash fs-2"></i>
					<i class="ki-duotone ki-eye fs-2 d-none"></i>
				</span>
			</div>
			<!--end::Input wrapper-->
			<!--begin::Meter-->
			<div class="d-flex align-items-center mb-3" data-kt-password-meter-control="highlight">
				<div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
				<div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
				<div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
				<div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px"></div>
			</div>
			<!--end::Meter-->
		</div>
		<!--end::Wrapper-->
		<!--begin::Hint-->
		<div class="text-muted">Use 8 or more characters with a mix of letters, numbers & symbols.</div>
		<!--end::Hint-->
	</div>
	<!--end::Input group=-->
	<!--end::Input group=-->
	<div class="fv-row mb-8">
		<!--begin::Repeat Password-->
		<input type="password" placeholder="Repeat Password" name="confirm-password" autocomplete="off" class="form-control bg-transparent" />
		<!--end::Repeat Password-->
	</div>
	<!--end::Input group=-->
	<!--begin::Input group=-->
	<div class="fv-row mb-8">
		<label class="form-check form-check-inline">
			<input class="form-check-input" type="checkbox" name="toc" value="1" />
			<span class="form-check-label fw-semibold text-gray-700 fs-6 ms-1">I Agree & 
			<a href="#" class="ms-1 link-primary">Terms and conditions</a>.</span>
		</label>
	</div>
	<!--end::Input group=-->
	<!--begin::Action-->
	<div class="d-grid mb-10">
		<button type="button" id="kt_new_password_submit" class="btn btn-primary">
			<!--begin::Indicator label-->
			<span class="indicator-label">Submit</span>
			<!--end::Indicator label-->
			<!--begin::Indicator progress-->
			<span class="indicator-progress">Please wait... 
			<span class="spinner-border spinner-border-sm align-middle ms-2"></span></span>
			<!--end::Indicator progress-->
		</button>
	</div>
	<!--end::Action-->
</form>
		{% include 'includes/includes_auth/aside_auth.html' %}

		<!--end::Aside-->
	</div>{% endblock %}
{% block custom_js %}
    <!--begin::Custom Javascript(used for this page only)-->
	<script src="{{ config.ASSETS_METRONIC_ROOT }}/js/custom/authentication/reset-password/new-password.js"></script>
    <!--end::Custom Javascript-->
{% endblock %}

apps/templates/authentication/sign-in.html
{% extends "layouts/authentication/base_auth.html" %}

{% block title %} INGRESAR {% endblock %}

{% block content_auth %}


<form class="form w-100" novalidate="novalidate" id="kt_sign_in_form" data-kt-redirect-url="index.html" action='{{ url_for("authentication_blueprint.register") }}'>
	<!--begin::Heading-->
	<div class="text-center mb-11">
		<!--begin::Title-->
		<h1 class="text-gray-900 fw-bolder mb-3">Sign In</h1>
		<!--end::Title-->
		<!--begin::Subtitle-->
		<div class="text-gray-500 fw-semibold fs-6">Your Social Campaigns</div>
		<!--end::Subtitle=-->
	</div>
	<!--begin::Heading-->
	<!--begin::Login options-->

	<!--end::Separator-->
	<!--begin::Input group=-->
	<div class="fv-row mb-8">
		<!--begin::Email-->
		<input type="text" placeholder="Email" name="email" autocomplete="off" class="form-control bg-transparent" />
		<!--end::Email-->
	</div>
	<!--end::Input group=-->
	<div class="fv-row mb-3">
		<!--begin::Password-->
		<input type="password" placeholder="Password" name="password" autocomplete="off"
			class="form-control bg-transparent" />
		<!--end::Password-->
	</div>
	<!--end::Input group=-->
	<!--begin::Wrapper-->
	<div class="d-flex flex-stack flex-wrap gap-3 fs-base fw-semibold mb-8">
		<div></div>
		<!--begin::Link-->
		<a href="{{ url_for('authentication_blueprint.forgot_password') }}" class="link-primary">Forgot Password ?</a>
		<!--end::Link-->
	</div>
	<!--end::Wrapper-->
	<!--begin::Submit button-->
	<div class="d-grid mb-10">
		<button type="submit" id="kt_sign_in_submit" class="btn btn-primary">
			<!--begin::Indicator label-->
			<span class="indicator-label">Sign In</span>
			<!--end::Indicator label-->
			<!--begin::Indicator progress-->
			<span class="indicator-progress">Please wait...
				<span class="spinner-border spinner-border-sm align-middle ms-2"></span></span>
			<!--end::Indicator progress-->
		</button>
	</div>
	<!--end::Submit button-->
	<!--begin::Sign up-->
	<div class="text-gray-500 text-center fw-semibold fs-6">Not a Member yet?
		<a href="{{ url_for('authentication_blueprint.register') }}" class="link-primary">Sign up</a>
	</div>
	<!--end::Sign up-->
</form>
{% endblock %}
{% block custom_js %}
<!--begin::Custom Javascript(used for this page only)-->
<script src="{{ config.ASSETS_METRONIC_ROOT }}/js/custom/authentication/sign-in/general.js"></script>
<!--end::Custom Javascript-->
{% endblock %}

apps/templates/authentication/sign-up.html
{% extends "layouts/authentication/base_auth.html" %}

{% block content_auth %}
<form class="form w-100" novalidate="novalidate" id="kt_sign_up_form" data-kt-redirect-url='{{ url_for("authentication_blueprint.verify_email") }}' action='{{ url_for("authentication_blueprint.register") }}' method="post">
	<!--begin::Heading-->
	<div class="text-center mb-11">
		<!--begin::Title-->
		<h1 class="text-gray-900 fw-bolder mb-3">Registrarse</h1>
		<!--end::Title-->
		<!--begin::Subtitle-->
		<div class="text-gray-500 fw-semibold fs-6">Tus Campañas Sociales</div>
		<!--end::Subtitle=-->
	</div>
	<!--begin::Heading-->

	<!--begin::Input group-->
	<div class="fv-row mb-8">
		<!--begin::Username-->
		<input type="text" placeholder="Nombre de usuario" name="username" autocomplete="off" class="form-control bg-transparent" />
		<!--end::Username-->
	</div>
	<!--end::Input group-->

	<!--begin::Input group-->
	<div class="fv-row mb-8">
		<!--begin::Email-->
		<input type="text" placeholder="Correo electrónico" name="email" autocomplete="off" class="form-control bg-transparent" />
		<!--end::Email-->
	</div>
	<!--end::Input group-->

	<!--begin::Input group-->
	<div class="fv-row mb-8">
		<!--begin::Phone-->
		<input type="text" placeholder="Teléfono" name="phone" autocomplete="off" class="form-control bg-transparent" />
		<!--end::Phone-->
	</div>
	<!--end::Input group-->

	<!--begin::Input group-->
	<div class="fv-row mb-8" data-kt-password-meter="true">
		<!--begin::Wrapper-->
		<div class="mb-1">
			<!--begin::Input wrapper-->
			<div class="position-relative mb-3">
				<input class="form-control bg-transparent" type="password" placeholder="Contraseña" name="password" autocomplete="off" />
				<span class="btn btn-sm btn-icon position-absolute translate-middle top-50 end-0 me-n2" data-kt-password-meter-control="visibility">
					<i class="ki-duotone ki-eye-slash fs-2"></i>
					<i class="ki-duotone ki-eye fs-2 d-none"></i>
				</span>
			</div>
			<!--end::Input wrapper-->
			<!--begin::Meter-->
			<div class="d-flex align-items-center mb-3" data-kt-password-meter-control="highlight">
				<div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
				<div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
				<div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
				<div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px"></div>
			</div>
			<!--end::Meter-->
		</div>
		<!--end::Wrapper-->
		<!--begin::Hint-->
		<div class="text-muted">Usa 8 o más caracteres con una combinación de letras, números y símbolos.</div>
		<!--end::Hint-->
	</div>
	<!--end::Input group-->

	<!--begin::Input group-->
	<div class="fv-row mb-8">
		<!--begin::Repeat Password-->
		<input placeholder="Repetir contraseña" name="confirm-password" type="password" autocomplete="off" class="form-control bg-transparent" />
		<!--end::Repeat Password-->
	</div>
	<!--end::Input group-->

	<!--begin::Accept-->
	<div class="fv-row mb-8">
		<label class="form-check form-check-inline">
			<input class="form-check-input" type="checkbox" name="toc" value="1" />
			<span class="form-check-label fw-semibold text-gray-700 fs-base ms-1">Acepto los 
			<a href="#" class="ms-1 link-primary">Términos</a></span>
		</label>
	</div>
	<!--end::Accept-->

	<!--begin::Submit button-->
	<div class="d-grid mb-10">
		<button type="submit" id="kt_sign_up_submit" class="btn btn-primary">
			<!--begin::Indicator label-->
			<span class="indicator-label">Registrarse</span>
			<!--end::Indicator label-->
			<!--begin::Indicator progress-->
			<span class="indicator-progress">Por favor, espera... 
			<span class="spinner-border spinner-border-sm align-middle ms-2"></span></span>
			<!--end::Indicator progress-->
		</button>
	</div>
	<!--end::Submit button-->

	<!--begin::Sign up-->
	<div class="text-gray-500 text-center fw-semibold fs-6">¿Ya tienes una cuenta? 
	<a href="{{ url_for('authentication_blueprint.login') }}" class="link-primary fw-semibold">Inicia sesión</a></div>
	<!--end::Sign up-->
</form>
{% endblock %}

{% block custom_js %}
    <!--begin::Custom Javascript(used for this page only)-->
	<script src="{{ config.ASSETS_METRONIC_ROOT }}/js/custom/authentication/sign-up/general.js"></script>
    <!--end::Custom Javascript-->
{% endblock %}